version: '3.5'
services:
  ez-housemode-synchronizer:
    image: ghcr.io/bblacey/ez-housemode-synchronizer
    network_mode: host
    env_file:
      - ./config.env
    environment:
      - NODE_ENV=production
    container_name: ez-housemode-synchronizer
    restart: unless-stopped
